CREATE TABLE [dbo].[Logement]
(
	[IdLogement] INT NOT NULL IDENTITY,
	[NomLogement] NVARCHAR(50) NOT NULL,
	[adresseRue] NVARCHAR(200) NOT NULL,
	[adresseNumero] INT NOT NULL,
	[adresseCodePostal] INT NOT NULL,
	[adressePays] NVARCHAR(50) NOT NULL,
	[DescriptionCourte] NVARCHAR(50) NOT NULL,
	[DescriptionLongue] NVARCHAR(250) NOT NULL,
	[DateCreation] DATE NOT NULL,
	[NombrePieces] INT NOT NULL,
	[PrixNuit] MONEY NOT NULL,
	[Capacite] INT NOT NULL,
	[SalleBain] INT NOT NULL,
	[Wc] INT NOT NULL,
	[Balcon] BIT NOT NULL DEFAULT 1,
	[AirConditionne] BIT NOT NULL,
	[Wifi] BIT NOT NULL DEFAULT 1,
	[MiniBar] BIT NOT NULL,
	[AnimauxAdmis] BIT NOT NULL DEFAULT 1,
	[Piscine] BIT NOT NULL DEFAULT 1,
	[RoomService] BIT NOT NULL,
	[Lattitude] INT NOT NULL,
	[Longitude] INT NOT NULL,
	[idTypeLogement] INT NOT NULL,
    CONSTRAINT [FK_Logement_ToTable] FOREIGN KEY ([IdTypeLogement]) REFERENCES [TypeLogement]([IdTypeLogement]),
	[IdClient] INT NOT NULL, 
    CONSTRAINT [FK_Logement_ToTable_1] FOREIGN KEY ([IdClient]) REFERENCES [Client]([IdClient]), 
    CONSTRAINT [PK_Logement] PRIMARY KEY ([IdLogement]), 
    CONSTRAINT [CK_Logement_DescriptionCourte] CHECK (LEN()>=25),
	CONSTRAINT [CK_Logement_DescriptionLongue] CHECK (LEN()>=250),
)
