CREATE TABLE [dbo].[Logement]
(
	[IdLogement] INT NOT NULL IDENTITY,
	[NomLogement] NVARCHAR(50) NOT NULL,
	[adresseRue] NVARCHAR(200) NOT NULL,
	[adresseNumero] NVARCHAR(50) NOT NULL,
	[adresseCodePostal] NVARCHAR(50) NOT NULL,
	[adressePays] NVARCHAR(50) NOT NULL,
	[DescriptionCourte] NVARCHAR(50) NOT NULL,
	[DescriptionLongue] NVARCHAR(512) NOT NULL,
	[DateCreation] DATE NOT NULL,
	[NombrePieces] TINYINT NOT NULL,
	[PrixNuit] MONEY NOT NULL,
	[Capacite] TINYINT NOT NULL,
	[SalleBain] TINYINT NOT NULL,
	[Wc] TINYINT NOT NULL,
	[Balcon] BIT NOT NULL DEFAULT 1,
	[AirConditionne] BIT NOT NULL,
	[Wifi] BIT NOT NULL DEFAULT 1,
	[MiniBar] BIT NOT NULL,
	[AnimauxAdmis] BIT NOT NULL DEFAULT 1,
	[Piscine] BIT NOT NULL DEFAULT 1,
	[RoomService] BIT NOT NULL,
	[Lattitude] DECIMAL(10,7) NOT NULL,
	[Longitude] DECIMAL(10,7) NOT NULL,
	[IdTypeLogement] INT NOT NULL,
    CONSTRAINT [FK_Logement_ToTable] FOREIGN KEY ([IdTypeLogement]) REFERENCES [TypeLogement]([IdTypeLogement]),
	[IdProprietaire] INT NOT NULL, 
    CONSTRAINT [FK_Logement_ToTable_1] FOREIGN KEY ([IdProprietaire]) REFERENCES [Proprietaire]([IdClient]), 
    CONSTRAINT [PK_Logement] PRIMARY KEY ([IdLogement]), 
    CONSTRAINT [CK_Logement_DescriptionCourte] CHECK (LEN([DescriptionCourte])>=8),
	CONSTRAINT [CK_Logement_DescriptionLongue] CHECK (LEN([DescriptionLongue])>=[DescriptionCourte])
)
